### ISSUE TITLE
AiC Source Code

### ISSUE THREAD

**Issue by wematan** [fabbrimatteo/AiC-Dataset#1]
Hi,

The code to this GTA mod will be released?

**Comment by fabbrimatteo** [comment]
Hi,

I am sorry but I am not planning to release the code. It is too messy and unfortunately I have no time to make a mod user friendly.

But, if you have any question regarding how to reimplement it, feel free to ask! It is an extension of the currently available mod that you can find [here](https://github.com/fabbrimatteo/JTA-Mods).

**Comment by wematan** [comment]
Hi,

Sure, I'd like to know how you recovered pedestrian attributes.
And if theres a possibility to spawn a custom attributes pedestrian?

Script hook v functions and explanations are also fine.

Thanks!

**Comment by fabbrimatteo** [comment]
I used [OpenIV](http://openiv.com/) to inspec all the pedestrian models in the game.
For each pedestrian model, you have fixed clothes that he can wear, in every possible combination. For example the model of the "old_lady_type_1" (I made up the name) can wear 2 types of pants and 2 types of shirts.
Then I mannually annotated the attributes triggered by those clothes (the pant one triggers Jeans while the other triggers tights for example).

At this poin I knew that spawning THAT pedestrian with those combination of clothes would generate a pedestrian with the combination of the attributes triggered by each type of clothes.

The next step was to spawn pedestrian and modify their appearances.

[This](http://www.dev-c.com/nativedb/) is a nice list of natives that you can call. You need PED::SET_PED_COMPONENT_VARIATION to set the clothes of each ped as you prefer. You can find more information [here](http://gtaxscripting.blogspot.com/2016/04/gta-v-peds-component-and-props.html).

This is the function I used to spawn a fixed ped (it is ugly code I know):
```
int Scenario::spawn_defined_ped(Vector3 pos) {

	if (this->json_idx == 49999)
		this->json_idx = 0;

	char* name = (char*)(root["population"][this->json_idx]["name"].asString()).c_str();
	Hash model = GAMEPLAY::GET_HASH_KEY(name);
	STREAMING::REQUEST_MODEL(model);
	while (!STREAMING::HAS_MODEL_LOADED(model))	WAIT(0);
	int id = PED::CREATE_PED(26, model, pos.x, pos.y, pos.z, 1, FALSE, TRUE);

	int has_glasses = 0;
	Json::Value codes = root["population"][this->json_idx]["code"];
	for (Json::ValueIterator itr = codes.begin(); itr != codes.end(); itr++) {
		Json::Value list = (*itr);
		std::vector<int> c;
		for (Json::ValueIterator itr2 = list.begin(); itr2 != list.end(); itr2++) {
			c.push_back((*itr2).asInt());
		}
		if (c[2] == -1) {
			int var = PED::GET_NUMBER_OF_PED_TEXTURE_VARIATIONS(id, c[0], c[1]);
			c[2] = rand() % var;
		}
		PED::SET_PED_COMPONENT_VARIATION(id, c[0], c[1], c[2], 0);

		
		int n_var = PED::GET_NUMBER_OF_PED_PROP_DRAWABLE_VARIATIONS(id, 1);
		if (n_var > 0) {
			if (random_float(0, 1) > 0.55) {
				int random_drawable = random_int(0, n_var);
				int n_texture = PED::GET_NUMBER_OF_PED_PROP_TEXTURE_VARIATIONS(id, 1, random_drawable);
				int random_texture = random_int(0, n_texture);
				PED::SET_PED_PROP_INDEX(id, 1, random_drawable, random_texture, 0);
				has_glasses = 1;
			}

		}
	}

	char* name_attr[] = {
		"sex",
		"age",
		"body",
		"hair",
		"hair_color",
		"hat",
		"muffler",
		"upper",
		"short_sleeve",
		"bottom",
		"shoes",
		"backpack"
	};
	int name_attr_len = 12;


	std::vector<int> annotations;
	for (int i = 0; i < name_attr_len; i++){
		Json::Value attributes = root["population"][this->json_idx]["attributes"][name_attr[i]];
		for (Json::ValueIterator itr = attributes.begin(); itr != attributes.end(); itr++) {
			annotations.push_back((*itr).asInt());
		}
	}
	annotations.push_back(has_glasses);

	this->json_idx += 1;

	addPedTrack(id, annotations);

	return id;
}
```
